# Setup
title:               A new knowledge node
tagline:             'A Jekyll theme, testing away'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 'http://Jakob37.github.io'
# url:                 https://lanyon.getpoole.com
baseurl:             'http://Jakob37.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/jakobwillforss
  email:             jakob@jakobwillforss.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
