# Setup
title:               Forest hut
tagline:             'A place for me and others to visit what I thought and built'
description:         'I like to think, to write, to build'
url:                 https://jakob37.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jakob Willforss
  url:               https://www.jakobwillforss.com
  email:             jakob@jakobwillforss.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
