# Setup
title:               A place to think and build
tagline:             '-'
description:         'A place to think and to build'
url:                 'https://Jakob37.github.io'
# url:                 https://lanyon.getpoole.com
baseurl:             'https://Jakob37.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jakob Willforss
  url:               https://twitter.com/jakobwillforss
  email:             jakob@jakobwillforss.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
